#set new value
#Thu Apr 03 17:29:23 ICT 2025
POSTGRES_TV_PLAY_TV_URL=jdbc\:postgresql\://10.54.10.35/tvplay-tv
TV_PLAY_TV_PASSWORD=Y2VhYzgwZTI3ZWRlOTMzYzc4MTA4ZWU2
TV_PLAY_ID_PASSWORD=YWNjMGJiM2FhOWFmN2Q2MDYzYmNjMDdk
TV_PLAY_ID_USER=tvplay-id
APP_ACTIVE=vn.vtvlive.ontv.a.feature.main.activity.MainActivity
APP_PACKAGE_ON_PLUS=com.vtvcab.onsports.dev
MONGO_DB_USER=
MY_SQL_TV_PLAY_UPLOAD=jdbc\:mysql\://10.54.10.32/tvplay-upload
SPECIAL_CHARACTER=\!@\#$%^&*()_+[]{}|;\:',.<>?/`~
NUMBER_DEVICE=1
PHONE_NUMBER=84363789036
PASS_WORD=123456
LIST_ID_DEVICE=R58M41M1AAZ
MONGO_DB_PASSWORD=MTQ5N2Y4MDY2MTNhOTJiYzQ4YjBhOTMz
MONGO_DB_CLIENT="mongodb\://10.54.10.32\:27017'
TV_PLAY_UPLOAD_PASSWORD=Mzc5ZDIxZjMyOGZjNjBjOWY4MmViNmYw
DB_EMAIL=vucuong@gmail.com
TV_PLAY_TV_USER=tvplay-tv
APP_PACKAGE=vn.vtvlive.ontv.a.dev
LIST_NAME_DEVICE=samsung
POSTGRES_TV_PLAY_ID_URL=jdbc\:postgresql\://10.54.10.35/tvplay-id
TV_PLAY_UPLOAD_USER=tvplay-upload
MONGO_TV_PLAY_ID_URL=mongodb\://tvplay-id\:MTQ5N2Y4MDY2MTNhOTJiYzQ4YjBhOTMz@10.54.10.32\:27017/?authSource\=tvplay-id
NUMBER_TEST_IN_SUITE=1
OVER_WRITE_REPORT=YES
