package locator;
import helpers.PropertiesFile;
import io.appium.java_client.AppiumBy;
import org.openqa.selenium.By;

public class Locator {
    public static final By NOTICE_BTN_OK = By.id("vn.vtvlive.ontv.a.dev:id/btnOk");
    public static final By NOTICE_BTN_CANCEL = By.id("vn.vtvlive.ontv.a.dev:id/btnCancel");
    public static final By BANNER_IMAGES = By.id("vn.vtvlive.ontv.a.dev:id/banner");
    public static final By BANNER_BTN_CLOSE = By.id("vn.vtvlive.ontv.a.dev:id/close");
    public static final By HOME_BTN_SEARCH = By.id("vn.vtvlive.ontv.a.dev:id/imageButtonSearch");
    public static final By HOME_BTN_SKIP = By.id("com.vtvcab.onsports.dev:id/skip");
    public static final By HOME_BTN_VIEW_MORE = By.id("vn.vtvlive.ontv.a.dev:id/view_more_text");
    public static final By HOME_BTN_MENU_PROFILE = By.id("vn.vtvlive.ontv.a.dev:id/menu_profile");
    public static final By HOME_BTN_HOME = By.id("vn.vtvlive.ontv.a.dev:id/menu_home");
    public static final By HOME_BTN_LIVE_SCORE = By.id("vn.vtvlive.ontv.a.dev:id/menu_livescore");
    public static final By HOME_BTN_NOTIFICATION = By.id("vn.vtvlive.ontv.a.dev:id/menu_notification");
    public static final By HOME_BTN_CATEGORY = By.id("vn.vtvlive.ontv.a.dev:id/menu_category");
    public static final By HOME_LBL_VIDEO_FOR_YOU = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title\" and @text=\"Dành cho bạn\"]");
    public static final By HOME_LAYOUT_CONTENTS = By.xpath("(//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/recycler_view\"]/androidx.appcompat.widget.LinearLayoutCompat)");
    public static final String HOME_LBL_TITLE_VIDEO_FOR_YOU = "(//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/recycler_view\"]/androidx.appcompat.widget.LinearLayoutCompat)[index]//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/video_live_list\"]//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_text\"]";
    public static final String HOME_LBL_TITLE_LIST_VIDEO_FOR_YOU = "(//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/recycler_view\"]/androidx.appcompat.widget.LinearLayoutCompat)[index]//androidx.appcompat.widget.LinearLayoutCompat[@resource-id=\"vn.vtvlive.ontv.a.dev:id/typeBlockSeeMore\"]//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title\"]";
    public static final String HOME_IMG_VIDEO_FOR_YOU = "(//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/recycler_view\"]/androidx.appcompat.widget.LinearLayoutCompat)[index]//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/video_live_list\"]//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/image\"]";
    public static final By HOME_VIDEO_LBL_LOGIN = By.id("vn.vtvlive.ontv.a.dev:id/tvMessage");
    public static final By HOME_VIDEO_BTN_LOGIN = By.id("vn.vtvlive.ontv.a.dev:id/btnAction");
    public static final By LOGIN_BTN = By.id("vn.vtvlive.ontv.a.dev:id/button_login");
    public static final By LOGIN_LBL_SOCIAL = By.id("vn.vtvlive.ontv.a.dev:id/guildTextSocial");
    public static final By LOGIN_BTN_GOOGLE = By.id("vn.vtvlive.ontv.a.dev:id/google");
    public static final By LOGIN_BTN_FACEBOOK = By.id("vn.vtvlive.ontv.a.dev:id/facebook");
    public static final By LOGIN_BTN_BACK = By.id("vn.vtvlive.ontv.a.dev:id/back_image");
    public static final By LOGIN_LBL_HELLO = By.id("vn.vtvlive.ontv.a.dev:id/hello");
    public static final By LOGIN_VIEW_REGISTER = By.id("vn.vtvlive.ontv.a.dev:id/emptyViewRegister");
    public static final By LOGIN_LBL_TITLE_LOGIN = By.xpath("//android.widget.TextView[@text=\"ĐĂNG NHẬP\"]");
    public static final By LOGIN_LBL_FORGOT_PASS = By.id("vn.vtvlive.ontv.a.dev:id/forgotPass");
    public static final By LOGIN_LBL_SUB_TITLE_LOGIN = By.id("vn.vtvlive.ontv.a.dev:id/sub_title_login");
    public static final By LOGIN_LBL_NOTICE_3_DEVICE = By.id("vn.vtvlive.ontv.a.dev:id/title_dialog");
    public static final By MENU_BTN_TERM_SERVICE = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/temrs\"]");
    public static final By MENU_BTN_VTV_INFORM = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/help\"]");
    public static final By LOGIN_BTN_CLOSE = By.id("vn.vtvlive.ontv.a.dev:id/cancelImageVIew");
    public static final By LOGIN_DDL_COUNTRY = By.xpath("//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/countryAndEditText\"]/android.widget.LinearLayout");
    public static final By LOGIN_TXT_USER_NAME = By.id("vn.vtvlive.ontv.a.dev:id/text_input");
    public static final By LOGIN_TXT_PASSWORD = By.id("vn.vtvlive.ontv.a.dev:id/text_input");
    public static final By LOGIN_BTN_CONTINUE = By.id("vn.vtvlive.ontv.a.dev:id/button_next");
    public static final By LOGIN_BTN_SHOW_PASS = By.id("vn.vtvlive.ontv.a.dev:id/ic_show_password");
    public static final By LOGIN_LBL_ERROR = By.id("vn.vtvlive.ontv.a.dev:id/text_error");
    public static final By LOGIN_TOAST_ERROR = By.id("vn.vtvlive.ontv.a.dev:id/tv_message");
    public static final By LOGIN_TOAST_INVALID_PASSWORD = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/infoTextView\"]");
    public static final By LOGIN_LOGO_FLAG = By.xpath("//android.widget.TextView[@text=\"VN\"]");
    public static final By LOGIN_TOAST_SUCCESS = By.id("vn.vtvlive.ontv.a.dev:id/tv_message");
    public static final By LOGIN_TOAST_LOGIN_SUCCESS = By.id("vn.vtvlive.ontv.a.dev:id/backgroundView");
    public static final By LOGIN_MESS_LOGIN_SUCCESS = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/infoTextView\"]");
    public static final By PROFILE_BTN_USER_ACCOUNT = By.id("vn.vtvlive.ontv.a.dev:id/profile");
    public static final By LOGOUT_BTN = By.id("vn.vtvlive.ontv.a.dev:id/layoutLogout");
    public static final By SIGN_UP_TIMELINE_OTP = By.id("vn.vtvlive.ontv.a.dev:id/text_error");
    public static final By SIGN_UP_BTN_RESEND_OTP = By.id("vn.vtvlive.ontv.a.dev:id/re_send_otp");
    public static final By SIGN_UP_LBL_TITLE_PHONE = By.id("vn.vtvlive.ontv.a.dev:id/title_phone");
    public static final By SIGN_UP_LBL_CONFIRM_PHONE_NUMBER = By.xpath("//android.widget.TextView[@text=\"XÁC THỰC SỐ ĐIỆN THOẠI\"]");
    public static final By SIGN_UP_LBL_SET_PASS = By.xpath("//android.widget.TextView[@text=\"ĐẶT MẬT KHẨU\"]");
    public static final By PROFILE_IMG_AVATAR = By.id("vn.vtvlive.ontv.a.dev:id/img_avatar");
    public static final By PROFILE_LBL_USER_NAME = By.id("vn.vtvlive.ontv.a.dev:id/txt_userName");
    public static final By PROFILE_BTN_MANAGE_DEVICE = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvTitle\" and @text=\"Quản lý thiết bị\"]");
    public static final By PROFILE_BTN_FOLLOW = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvTitle\" and @text=\"Theo dõi\"]");
    public static final By PROFILE_BTN_VIEW_LATER = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvTitle\" and @text=\"Xem sau\"]");
    public static final By PROFILE_BTN_INFORM_ON_LIVE = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvTitle\" and @text=\"Thông tin về ON Live TV\"]");
    public static final By PROFILE_BTN_TERM_AND_SERVICE = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvTitle\" and @text=\"Điều khoản dịch vụ\"]");
    public static final By PROFILE_ACCOUNT_BTN_EDIT = By.id("vn.vtvlive.ontv.a.dev:id/tvEdit");
    public static final By PROFILE_ACCOUNT_BTN_CONFIRM_EDIT = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvEdit\"]");
    public static final By PROFILE_ACCOUNT_BTN_BACK = By.id("vn.vtvlive.ontv.a.dev:id/image_back");
    public static final By PROFILE_ACCOUNT_BTN_CHANGE_PASS = By.id("vn.vtvlive.ontv.a.dev:id/imgChangePass");
    public static final By EDIT_ACCOUNT_BTN_EDIT_BIRTH_DAY = By.id("vn.vtvlive.ontv.a.dev:id/imgChoiceCal");
    public static final By PROFILE_ACCOUNT_LBL_BIRTH_DAY = By.id("vn.vtvlive.ontv.a.dev:id/tvBirthday");
    public static final By EDIT_ACCOUNT_BTN_EDIT_NAME = By.id("vn.vtvlive.ontv.a.dev:id/edtFullName");
    public static final By EDIT_ACCOUNT_BTN_EDIT_EMAIL = By.id("vn.vtvlive.ontv.a.dev:id/edtEmail");
    public static final By EDIT_ACCOUNT_BTN_CHANGE_PASS = By.id("vn.vtvlive.ontv.a.dev:id/tvPassword");
    public static final By EDIT_ACCOUNT_BTN_EDIT_PHONE = By.id("vn.vtvlive.ontv.a.dev:id/edtPhone");
    public static final By LOGOUT_BTN_CONFIRM = By.id("vn.vtvlive.ontv.a.dev:id/btnOk");
    public static final By LOGOUT_BTN_CANCEL = By.id("vn.vtvlive.ontv.a.dev:id/btnCancel");
    public static final By LOGOUT_TITLE_POP_UP = By.id("vn.vtvlive.ontv.a.dev:id/message");
    public static final String  DATE_PICKER_BTN_DATE = "//android.view.View[@text='day']";
    public static final By DATE_PICKER_LBL_YEAR = By.id("android:id/date_picker_header_year");
    public static final By DATE_PICKER_LBL_DATE = By.id("android:id/date_picker_header_date");
    public static final By DATE_PICKER_BTN_NEXT = By.id("android:id/next");
    public static final By DATE_PICKER_BTN_PRE = By.id("android:id/prev");
    public static final By DATE_PICKER_BTN_OK = By.id("android:id/button1");
    public static final By DATE_PICKER_BTN_CANCEL = By.id("android:id/button2");
    public static final By ANDROID_PHOTO_APP = By.id("com.google.android.apps.photos:id/fragment_container");
    public static final By CHANGE_PASSWORD_TXT_CURRENT = By.xpath("//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ed_password\"]//android.widget.EditText[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_input\"]");
    public static final By CHANGE_PASSWORD_TXT_NEW_PASS = By.xpath("//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ed_new_password\"]//android.widget.EditText[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_input\"]");
    public static final By CHANGE_PASSWORD_TXT_NEW_PASS_AGAIN = By.xpath("//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ed_password_again\"]//android.widget.EditText[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_input\"]");
    public static final By CHANGE_PASSWORD_LBL_ERROR = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_error\" and @text=\"Mật khẩu phải từ 6 kí tự trở lên\"]");
    public static final By CHANGE_PASSWORD_LBL_ERROR_SAME_PASS = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_error\" and @text=\"Mật khẩu không trùng khớp\"]");
    public static final By CHANGE_PASSWORD_LBL_INCORRECT_PASS = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_error\" and @text=\"Mật khẩu không chính xác\"]");
    public static final By CHANGE_PASSWORD_BTN_SHOW_PASS = By.xpath("(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_show_password\"])[1]");
    public static final By CHANGE_PASSWORD_BTN_SHOW_PASS_2 = By.xpath("(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_show_password\"])[2]");
    public static final By CHANGE_PASSWORD_BTN_SHOW_PASS_3 = By.xpath("(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_show_password\"])[3]");
    public static final By LOGOUT_TOAST_SUCCESS = By.id("vn.vtvlive.ontv.a.dev:id/tv_message");
    public static final By LOGIN_TXT_CONFIRM_PASSWORD = By.xpath("//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ed_password_again\"]//android.widget.EditText[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_input\"]");
    public static final By USER_INFORM_TOAST_UPDATE_FAIL_NAME = By.xpath("//android.widget.Toast[@text=\"Vui lòng nhập tên\"]");
    public static final By USER_INFORM_TOAST_UPDATE_FAIL_EMAIL = By.xpath("//android.widget.Toast[@text=\"Vui lòng đúng định dạng email\"]");
    public static final By POLICY_TERM_LBL_TITLE  = By.xpath("//android.view.View[@text=\"CHÍNH SÁCH BẢO MẬT & ĐIỀU KHOẢN SỬ DỤNG\"]");
    public static final String SIGN_UP_TXT_EDIT_OPT = "vn.vtvlive.ontv.a.dev:id/textindex";
    public static final By SIGN_UP_TXT_ENTER_OPT = By.id("vn.vtvlive.ontv.a.dev:id/enter6CodeOTP");
    public static final By DEVICE_MANAGER_LBL_CURRENT = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/info\" and @text=\"Đang đăng nhập thiết bị\"]");
    public static final By DEVICE_MANAGER_LBL_TITLE = By.xpath("//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/toolbar\"]//android.widget.TextView");
    public static final By DEVICE_MANAGER_BTN_LOGOUT = By.xpath("(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/button_logout\"])[1]");
    public static final By DEVICE_MANAGER_LBL_NAME_DEVICE = By.xpath("(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/deviceName\"])[1]");
    public static final By DEVICE_MANAGER_BTN_LAYOUT_DEVICE = By.xpath("(//android.widget.RelativeLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/layoutDevice\"])[1]");
    public static final String DEVICE_MANAGER_LBL_NAME_DEVICES = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/deviceName\"])";
    public static final By FOLLOWING_LBL_TITLE = By.xpath("//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/toolbar\"]//android.widget.TextView");
    public static final By FOLLOWING_BTN_CANCEL_FOLLOW = By.id("vn.vtvlive.ontv.a.dev:id/tvCancelFollowAll");
    public static final By INFORM_ON_LIVE_TV_LBL_TITLE = By.id("vn.vtvlive.ontv.a.dev:id/title");
    public static final By LATE_VIEW_BTN_DELETE_ALL = By.id("vn.vtvlive.ontv.a.dev:id/tvDeleteWatchLaterAll");
    public static final By LATE_VIEW_LBL_TITLE = By.xpath("//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/toolbar\"]//android.widget.TextView");
    public static final By LATE_VIEW_BTN_VIDEO = By.xpath("(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/image\"])[1]");
    public static final By LATE_VIEW_BTN_DELETE = By.xpath("(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvStatusFollow\"])[1]");
    public static final By LATE_VIEW_LIST_VIDEO = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/recycler_view\"]");
    public static final By LATE_VIEW_LBL_NAME_VIDEO = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_text\"]");
    public static final By LATE_VIEW_LBL_FIRST_NAME_VIDEO = By.xpath("(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_text\"])[1]");
    public static final String LATE_VIEW_LBL_NAME_VIDEO_DELETED = "//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_text\" and @text=\"key\"]";
    public static final By LATE_VIEW_LBL_EMPTY_VIDEO = By.id("vn.vtvlive.ontv.a.dev:id/lottieNotFound");
    public static final By TERM_AND_POLICY_DOCUMENT = By.id("vn.vtvlive.ontv.a.dev:id/base_view");
    public static final By FORGOT_PASSWORD_BTN_FORGOT = By.id("vn.vtvlive.ontv.a.dev:id/forgot_paassword");
    public static final By FORGOT_PASSWORD_LBL_TITLE_FORGOT = By.xpath("//android.widget.TextView[@text=\"ĐẶT MẬT KHẨU\"]");
    public static final By FORGOT_PASSWORD_LBL_ERROR_1 = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_error\"])[1]");
    public static final By FORGOT_PASSWORD_LBL_ERROR_2 = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_error\"])[2]");
    public static final By FORGOT_PASSWORD_BTN_SHOW_PASS_1 = By.xpath("//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_show_password\"])[1]");
    public static final By FORGOT_PASSWORD_BTN_SHOW_PASS_2 = By.xpath("//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_show_password\"])[2]");
    public static final By FORGOT_PASSWORD_LBL_ERROR_SAME_PASS = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/text_error\" and @text=\"Mật khẩu không trùng nhau\"]");
    public static final By MATCH_SCHEDULE_BTN_TODAY = By.id("vn.vtvlive.ontv.a.dev:id/today_text");
    public static final By MATCH_SCHEDULE_BTN_CALENDAR = By.id("vn.vtvlive.ontv.a.dev:id/imgCalendar");
    public static final By MATCH_SCHEDULE_BTN_CATEGORY = By.id("vn.vtvlive.ontv.a.dev:id/rcv_category_game");
    public static final By MATCH_SCHEDULE_BTN_ALL = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\" and @text=\"Tất cả\"]");
    public static final By MATCH_SCHEDULE_LBL_LIST_MATCH = By.id("vn.vtvlive.ontv.a.dev:id/rcv_live_score");
    public static final By MATCH_SCHEDULE_LBL_EMPTY_MATCH = By.id("vn.vtvlive.ontv.a.dev:id/empty_livescore");
    public static final By MATCH_SCHEDULE_LBL_TITLE_EMPTY_MATCH = By.xpath("//android.widget.TextView[@text=\"KHÔNG CÓ TRẬN ĐẤU NÀO\"]");
    public static final String MATCH_SCHEDULE_LBL_MATCH = "//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/rcv_live_score\"]/android.widget.RelativeLayout";
    public static final String MATCH_SCHEDULE_LBL_TIME_MATCH = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/timeMatch\"])[index]";
    public static final By MATCH_SCHEDULE_LBL_TIME_MATCH_ID = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/timeMatch\"]");
    public static final String MATCH_SCHEDULE_LBL_NAME_TOURNAMENT = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/name_tournament\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_NAME_CATEGORY = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/name_category\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_TEAM_HOME = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/name_team_home\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_TEAM_AWAY = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/name_team_away\"])[index]";
    public static final String MATCH_SCHEDULE_IMG_TEAM_HOME = "(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_team_home\"])[index]";
    public static final String MATCH_SCHEDULE_IMG_TEAM_AWAY = "(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_team_away\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_RESULT = "(//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/results_parent\"])[index]";
    public static final By MATCH_SCHEDULE_LBL_LINE_DATE = By.xpath("(//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/calendar_linear_layout\"])");
    public static final String MATCH_SCHEDULE_LBL_DAY = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/txt_day\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_DATE_MONTH = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/txt_date\"])[index]";
    public static final String MATCH_SCHEDULE_CALENDER_BTN_DATE = "//android.view.View[@resource-id=\"android:id/month_view\"]//android.view.View[@text='day']";
    public static final By MATCH_SCHEDULE_CALENDER_LBL_VIEW_MONTH = By.xpath("//android.view.View[@resource-id=\"android:id/month_view\"]");

    public static final By MATCH_SCHEDULE_BTN_TAB_CATEGORY = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\"]");
    public static final String MATCH_SCHEDULE_BTN_TAB_CATEGORIES ="(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\"])[index]";
    public static final By MATCH_SCHEDULE_BTN_CONTENTS = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/rcv_live_score\"]/android.widget.RelativeLayout[1]");
    public static final By MATCH_SCHEDULE_IMG_CATEGORY_DETAIL = By.xpath("//android.widget.FrameLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/image_layout\"]/android.view.ViewGroup/android.view.View");
    public static final By MATCH_SCHEDULE_DETAIL_BTN_FOLLOWING = By.id("vn.vtvlive.ontv.a.dev:id/following_parent");
    public static final By MATCH_SCHEDULE_DETAIL_LBL_TITLE = By.id("vn.vtvlive.ontv.a.dev:id/title_category");
    public static final By MATCH_SCHEDULE_BTN_SHOW = By.xpath("(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/btn_show\"])");
    public static final String MATCH_SCHEDULE_LBL_TOP_3_TEAM = "(//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/top_3_teams\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_NAME_TOP1 = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/name_top_1\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_NAME_TOP2 = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/name_top_2\"])[index]";
    public static final String MATCH_SCHEDULE_LBL_NAME_TOP3 = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/name_top_3\"])[index]";






    public static final String CATEGORY_LBL_TITLE = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\"])[index]";
    public static final String CATEGORY_LBL_TITLE_TEXT = "//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\" and @text=\"key\"]";
    public static final String CATEGORY_LBL_DESCRIPTION = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/desciption_category\"])[index]";
    public static final By CATEGORY_LBL_LOGO = By.id("vn.vtvlive.ontv.a.dev:id/logo");
    public static final By CATEGORY_BTN_SEARCH = By.id("vn.vtvlive.ontv.a.dev:id/imageButtonSearch");
    public static final By CATEGORY_BTN_PIN = By.xpath("(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/pinImageView\"])[1]");
    public static final String CATEGORY_BTN_PINS = "(//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/layoutCategory\"])[index]//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/pinImageView\"]";
    public static final String CATEGORY_LBL_TITLES = "(//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/layoutCategory\"])[index]//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\"]";
    public static final By CATEGORY_FIRST_BTN_DETAIL = By.id("vn.vtvlive.ontv.a.dev:id/ic_detail");
    public static final String CATEGORY_DETAILS_LBL_TITLE = "//android.widget.FrameLayout[@content-desc=\"title\"]";
    public static final By CATEGORY_THUMBNAIL_IMG = By.xpath("//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/thumbnail_image\"]");
    public static final By CATEGORY_DETAIL_BTN_CLOSE = By.id("vn.vtvlive.ontv.a.dev:id/action_back");
    public static final By CATEGORY_DETAIL_IMG = By.id("vn.vtvlive.ontv.a.dev:id/app_bar_layout");
    public static final String CATEGORY_BTN_TABS ="(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/logo_category\"])[index]";
    public static final By CATEGORY_BTN_TAB = By.xpath("//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/logo_category\"]");
    public static final By CATEGORY_DETAIL_TITLE_FIRST_TAB = By.xpath("(//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/parent_item\"])[1]//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\"]");
    public static final String CATEGORY_DETAIL_TITLE_TABS = "(//android.view.ViewGroup[@resource-id=\"vn.vtvlive.ontv.a.dev:id/parent_item\"])[index]//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_category\"]";
    public static final By CATEGORY_DETAIL_LBL_EMPTY = By.id("vn.vtvlive.ontv.a.dev:id/empty_layout");
    public static final By CATEGORY_DETAIL_TITLE_EMPTY = By.xpath("(//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/empty_layout\"]//android.widget.TextView)[1]");
    public static final By CATEGORY_DETAIL_SUB_TITLE_EMPTY = By.xpath("(//android.widget.LinearLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/empty_layout\"]//android.widget.TextView)[2]");
    public static final By CATEGORY_DETAIL_TITLE_EVENT_VIDEO = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_event\" and @text=\"Video\"]");
    public static final By CATEGORY_DETAIL_TITLE_EVENT = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/title_event\" and @text=\"Sự kiện\"]");
    public static final By CATEGORY_DETAIL_BTN_LOAD_MORE = By.id("vn.vtvlive.ontv.a.dev:id/loadMoreButton");
    public static final By CATEGORY_DETAIL_TITLE_NAME_EVENT = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/nameOfEvent\"]");
    public static final By CATEGORY_DETAIL_TXT_LIVE = By.id("vn.vxpaxpatvlive.ontv.a.dev:id/include_live_text");
    public static final By CATEGORY_DETAIL_BTN_LEAGUE = By.xpath("(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/txtLeague\"])");
    public static final By CATEGORY_DETAIL_BTN_CATEGORY = By.xpath("(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/txtCategory\"])");
    public static final By CATEGORY_DETAIL_LBL_UP_COMING = By.xpath("//androidx.appcompat.widget.LinearLayoutCompat[@resource-id=\"vn.vtvlive.ontv.a.dev:id/include_incoming_text\"]");
    public static final By CATEGORY_DETAIL_BTN_IC_MORE = By.xpath("//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_more\"]");
    public static final String CATEGORY_DETAIL_BTN_IC_MORE_INDEX = "//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/rcv_category\"]/android.view.ViewGroup[index]//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/ic_more\"]";
    public static final By CATEGORY_DETAIL_BTN_SET_NOTICE = By.id("vn.vtvlive.ontv.a.dev:id/ic_group1");
    public static final By CATEGORY_DETAIL_BTN_SHARE = By.id("vn.vtvlive.ontv.a.dev:id/txt_group2");

    public static final By CATEGORY_DETAIL_NOTICE_LBL_TITLE = By.id("vn.vtvlive.ontv.a.dev:id/top");
    public static final String CATEGORY_DETAIL_BTN_THUMB_IMG ="(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/thumbnailImageView\"])[index]";

    public static final String CATEGORY_DETAIL_BTN_VOD_THUMB_IMG ="(//android.widget.ImageView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/image\"])[index]";
    public static final By CATEGORY_DETAIL_PLAYER_VOD = By.xpath("//android.widget.RelativeLayout[@resource-id=\"vn.vtvlive.ontv.a.dev:id/exo_player_view\"]");
    public static final By CATEGORY_DETAIL_PLAYER_LBL_LIVE = By.id("vn.vtvlive.ontv.a.dev:id/ivLive");
    public static final By CATEGORY_DETAIL_LBL_VIEW = By.xpath("//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/rcv_category\"]/android.view.ViewGroup");
    public static final String CATEGORY_DETAIL_LBL_EVENT_COMING ="//androidx.recyclerview.widget.RecyclerView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/rcv_category\"]/android.view.ViewGroup[index]//androidx.appcompat.widget.LinearLayoutCompat[@resource-id=\"vn.vtvlive.ontv.a.dev:id/include_incoming_text\"]";
    public static final By CATEGORY_DETAIL_LIST_TAB = By.id("vn.vtvlive.ontv.a.dev:id/rcv_tag");
    public static final String CATEGORY_DETAIL_BTN_LEAGUE_INDEX = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/txtLeague\"])[index]";
    public static final String CATEGORY_DETAIL_BTN_LEAGUE_VOD_INDEX = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvLeague\"])[index]";
    public static final String CATEGORY_DETAIL_BTN_CATEGORY_INDEX = "(//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/txtCategory\"])[index]";

    public static final By CATEGORY_DETAIL_PLAYER_BTN_SAVE = By.id("vn.vtvlive.ontv.a.dev:id/btnSaved");
    public static final By CATEGORY_DETAIL_PLAYER_LBL_TITLE = By.id("vn.vtvlive.ontv.a.dev:id/tvTitle");
    public static final By CATEGORY_DETAIL_PLAYER_BTN_CATEGORY = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvCategory\"]");
    public static final By CATEGORY_DETAIL_PLAYER_BTN_LEAGUE = By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/tvLeague\"]");
    public static final By CATEGORY_DETAIL_LEAGUE_BTN_FOLLOW = By.id("vn.vtvlive.ontv.a.dev:id/txt_followed");
    public static final By CATEGORY_DETAIL_VOD_LBL_TIME= By.xpath("//android.widget.TextView[@resource-id=\"vn.vtvlive.ontv.a.dev:id/duration_text\"]");







}

